config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from web import views

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('web.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path,include
from .views import index, functionsView, BlogsView, blogDetailView, updateView, \
deleteBlogView, BlogCreate, BlogCategoryCreate


app_name = "main"

urlpatterns = [
    path('', index.as_view(), name="index"),
    path('function/<int:pk>/', functionsView.as_view(), name="functionsView"),
    path('blogs/list/', BlogsView.as_view(), name="BlogsView"),
    path('blog/detail/<int:pk>/', blogDetailView.as_view(), name="blogDetailView"),
    path('blog/create/', BlogCreate.as_view(), name="BlogCreate"),
    path('add/blog/category/', BlogCategoryCreate.as_view(), name="BlogCategoryCreate"),
    path('update/blog/<int:pk>/', updateView.as_view(), name="updateView"),
    path('delete/blog/<int:pk>/', deleteBlogView, name="deleteBlogView"),
]

templates/pages/blogcategorycreate.html
{% extends 'layout/base.html' %}
{% load static %}

{% block pathUrl %}
<a href="{% url 'main:index' %}">Home</a> /
Add Blog Category 
{% endblock %}

{% block content %}
<section class="content-section">
    <div class="content-container">
        <form class="content-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="content-form-input-container">
                {{ form }}
            </div>

            <div class="content-form-submit">
                <button type="Submit">Submit</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block js_block %}
<script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js"></script>
{% endblock %}

templates/pages/blogcreate.html
{% extends 'layout/base.html' %}
{% load static %}

{% block pathUrl %}
<a href="{% url 'main:index' %}">Home</a> /
Blog Create 
{% endblock %}

{% block content %}
<section class="content-section">
    <div class="content-container">
        <form class="content-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="content-form-input-container">
                {{ form.media }}
                {{ form }}
            </div>

            <div class="content-form-submit">
                <button type="Submit">Submit</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block js_block %}
<script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js"></script>
{% endblock %}

templates/pages/blogdetail.html
{% extends 'layout/base.html' %}
{% load static %}

{% block pathUrl %}
    <a href="{% url 'main:index' %}">Home</a> /
    <a href="{% url 'main:BlogsView' %}">Blogs</a> / 
    {{ object.title }} 
{% endblock %}

{% block content %}
<section class="content-section blog">
    <div class="content-container">
        <article class="content-article blog">
            <h1 class="content-title">{{ object.title }}</h1>
            {{ object.text|safe }}
        </article>

        <div class="blog-content">
            <img src="{{ object.image.url }}" alt="">
            {% if request.user == object.user %}
            <div class="blog-content-changers">
                <a href="{% url 'main:updateView' pk=object.pk %}">Update <i class="fa-solid fa-pen"></i></a>
                <button id="deleteAsking">Delete <i class="fa-solid fa-trash"></i></button>
                {% include 'pages/deleteblog.html' %}
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

{% block js_block %}
<script>
    var btn = document.getElementById('deleteAsking');
    var modal = document.getElementById('deleteModal-wrapper');
    var cancelBtn = document.getElementById('cancel-delete');

    btn.addEventListener('click', function () {
        modal.classList.add('active');
    });

    cancelBtn.addEventListener('click', function () {
        modal.classList.remove('active');
    });
    
</script>
{% endblock %}

templates/pages/blogs.html
{% extends 'layout/base.html' %}
{% load static %}

{% block pathUrl %}
<a href="{% url 'main:index' %}">Home</a> /
Blogs
{% endblock %}

{% block content %}
<section class="content-section">
    <div class="content-container">
        {% if request.user.is_authenticated %}
        <article class="blog-create">
            <a href="{% url 'main:BlogCreate' %}" class="create-blog-link">+ Add new blog</a>
        </article>
        {% endif %}
        <div class="blogs-container">
            {% for object in object_list %}
            <a href="{% url 'main:blogDetailView' pk=object.pk %}" class="blog-object">
                <article class="blog-category-container">
                    <h1 class="blog-category">{{ object.category }}</h1>
                    <p class="blog-created-at">{{ object.created_at|date:"d M, Y" }}</p>
                </article>
                <div class="blog-content-container">
                    <h1 class="blog-title">{{ object.title }}</h1>
                    <p class="blog-text" id="blog-text">{{ object.text|safe }}</p>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block js_block %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const blogs = document.querySelectorAll('.blog-object');
        const blogText = document.getElementById('blog-text');

        blogs.forEach((blog, index) => {
            const patternIndex = index % 3;

            if (patternIndex === 0) {
                blog.style.gridColumn = 'span 5';
                blog.style.height = '20rem';
            } else if (patternIndex === 1) {
                blog.style.gridColumn = 'span 3';
            } else if (patternIndex === 2) {
                blog.style.gridColumn = 'span 2';
            }
        });
    });
</script>
{% endblock %}

templates/pages/change.html
{% extends 'layout/base.html' %}
{% load static %}

{% block pathUrl %}<a href="{% url 'main:index' %}">Home</a> / {{ object.title }} {% endblock %}

{% block content %}
<section class="content-section">
    <div class="content-container">
        <article class="content-article">
            <h1 class="content-title">What is <span class="primary-word">{{ object.title }}</span> Function in Django ?</h1>
            <p class="content-description">{{ object.description }}</p>
        </article>
        <div class="content-list">
            <div class="content-list-container">
                <h1 class="content-list-title">Here is the list of blogs that you can change</h1>
                <div class="content-list-object-wrapper">
                    {% for object in blogs %}
                        <a href="{% url 'main:blogDetailView' pk=object.pk %}">
                            <div class="content-list-object">
                                <div class="content-list-object-image-container"
                                    style="background-image: url('{{ object.image.url }}');">
                                    <h1 class="content-list-object-title">{{ object.title }}</h1>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js_block %}

{% endblock %}

templates/pages/deleteblog.html
<div class="deleteModal-wrapper" id="deleteModal-wrapper">
    <div id="deleteModal" class="delete-modal">
        <div class="modal-content">
            <p>Are you sure you want to delete this blog?</p>
            <form class="modal-content-buttons-container" action="{% url 'main:deleteBlogView' pk=object.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" id="confirm-delete" class="confirm-delete">Delete <i class="fa-solid fa-trash"></i></button>
                <button type="button" id="cancel-delete" class="cancel-delete">Cancel <i class="fa-solid fa-xmark"></i></button>
            </form>
        </div>
    </div>
</div>

templates/pages/index.html
{% extends 'layout/base.html' %}
{% load static %}

{% block content %}
<section class="content-section">
    <div class="content-container">
        <article class="content-article">
            <h1 class="content-title">Управление ИТ-активами – скучная рутина или творческая задача?</h1>
            <p class="content-description">Размышляя об управлении ИТ-активами, я вспомнил один учебный пример. Менеджер
                по ИТ-мощностям в крупной компании периодически готовил толстенный отчёт руководству. В очередной раз он
                не принёс отчёт, решив проверить, нужен ли он вообще. </p>
        </article>

        <div class="content-list">
            <div class="content-list-container">
                <h1 class="content-list-title">Here is the functions list</h1>
                <div class="content-list-object-wrapper">
                    {% for object in object_list %}
                    <a href="{% url 'main:functionsView' pk=object.pk  %}">
                        <div class="content-list-object">
                            <div class="content-list-object-image-container"
                                style="background-image: url('{% static 'main/images/main/blog.jpg' %}');">
                                <h1 class="content-list-object-title">{{ object.title }}</h1>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block js_block %}

{% endblock %}

templates/pages/updateactive.html
{% extends 'layout/base.html' %}
{% load static %}

{% block pathUrl %}
<a href="{% url 'main:index' %}">Home</a> /

{{ object.title }}
{% endblock %}

{% block content %}
<section class="content-section">
    <div class="content-container">
        <form class="content-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="content-form-input-container">
                {{ form.media }}
                {{ form }}
            </div>

            <div class="content-form-submit">
                <button type="Submit">Submit</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}

{% block js_block %}
<script src="https://cdn.ckeditor.com/ckeditor5/36.0.1/classic/ckeditor.js"></script>
{% endblock %}